# Generated by Django 5.2 on 2025-05-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room_name',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
